ALTER VIEW [Количество кафедр] WITH SCHEMABINDING
	as SELECT dbo.FACULTY.FACULTY_NAME факультет, COUNT(dbo.PULPIT.PULPIT) [количество кафедр]
	FROM dbo.FACULTY INNER JOIN dbo.PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
	GROUP BY FACULTY.FACULTY_NAME;