
CREATE TABLE KFA_TABLE (
    ID NUMBER(3),
    TEXT VARCHAR2(40)
);

SELECT * FROM DICT 
     WHERE TABLE_NAME LIKE '%USER%';
     
SELECT * FROM USER_TABLESPACES;

SELECT * FROM ALL_FILE_GROUP_FILES;

SELECT * FROM USER_ROLE_PRIVS;

SELECT * FROM ROLE_SYS_PRIVS;

SELECT * FROM ALL_USERS;

select * from DBA_TABLESPACES; 
select * from DBA_ROLES;
select * from DBA_PROFILES;
select * from ALL_USERS;
select * from DBA_DATA_FILES;
select * from DBA_TEMP_FILES; 

SELECT * FROM USER_CATALOG;