CREATE TABLE KFA_t(
    person_id NUMBER(3) GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    PRIMARY KEY(person_id)
);

insert into KFA_t
values (12, 'Fedos', 'Krutytsky');

insert into KFA_t
values (171, 'asdfl', 's');

COMMIT comment 'коммит с комментарием';

update KFA_t
set first_name = 'New'
where person_id = 171;

Select * from KFA_t;

COMMIT comment 'опять коммит с комментарием';

select avg(person_id)
from KFA_t;

DELETE FROM KFA_t WHERE person_id = 171;
ROLLBACK;


CREATE TABLE KFA_t_child(
    post_id NUMBER(3) GENERATED BY DEFAULT AS IDENTITY,
    post_description varchar2(59),
    author number(3),
    foreign key (author)
    references KFA_t(person_id),
    PRIMARY KEY(post_id)
);

insert into KFA_t_child(post_description, author)
values ('Posted', 171);

SELECT post_description, person_id
FROM KFA_t
LEFT JOIN KFA_t_child
ON KFA_t.person_id = KFA_t_child.author;

SELECT post_description, person_id
FROM KFA_t
inner JOIN KFA_t_child
ON KFA_t.person_id = KFA_t_child.author;

drop table KFA_t_child;
drop table KFA_t;