USE UNIVER;

SELECT PULPIT.PULPIT_NAME
FROM PULPIT, FACULTY
WHERE PULPIT.FACULTY = FACULTY.FACULTY AND
FACULTY.FACULTY IN (SELECT PROFESSION.FACULTY 
FROM PROFESSION 
WHERE PROFESSION.PROFESSION_NAME LIKE '%технология%' or 
PROFESSION.PROFESSION_NAME LIKE '%технологии%');

SELECT DISTINCT PULPIT.PULPIT_NAME
FROM PULPIT, FACULTY INNER JOIN PROFESSION ON FACULTY.FACULTY = PROFESSION.FACULTY
WHERE PULPIT.FACULTY = FACULTY.FACULTY AND
(PROFESSION.PROFESSION_NAME LIKE '%технология%' or 
PROFESSION.PROFESSION_NAME LIKE '%технологии%');

SELECT DISTINCT PULPIT.PULPIT_NAME
FROM PULPIT INNER JOIN FACULTY ON PULPIT.FACULTY = FACULTY.FACULTY INNER JOIN
PROFESSION ON FACULTY.FACULTY = PROFESSION.FACULTY
WHERE PROFESSION.PROFESSION_NAME LIKE '%технология%' or 
PROFESSION.PROFESSION_NAME LIKE '%технологии%';

SELECT AUDITORIUM_NAME, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
FROM AUDITORIUM a
WHERE AUDITORIUM_NAME = (SELECT top(1) AUDITORIUM_NAME
FROM AUDITORIUM b
WHERE a.AUDITORIUM_TYPE = b.AUDITORIUM_TYPE
ORDER BY AUDITORIUM_CAPACITY DESC);

SELECT PULPIT_NAME
FROM PULPIT
WHERE not exists (select *
	from FACULTY
	where FACULTY.FACULTY = PULPIT.FACULTY);

SELECT (select avg(NOTE) from PROGRESS where SUBJECT = 'ОАиП')[ОАиП],
(select avg(NOTE) from PROGRESS where SUBJECT = 'КГ')КГ,
(select avg(NOTE) from PROGRESS where SUBJECT = 'СУБД')СУБД;

SELECT IDSTUDENT, SUBJECT, NOTE
FROM PROGRESS a	
WHERE NOTE >= all(select note from PROGRESS b where a.SUBJECT = b.SUBJECT)

SELECT IDSTUDENT, SUBJECT, NOTE
FROM PROGRESS
WHERE NOTE > any (select note from PROGRESS where SUBJECT = 'СУБД') AND SUBJECT = 'СУБД';

SELECT NAME, BDAY
FROM STUDENT a
WHERE BDAY IN (SELECT BDAY FROM STUDENT b WHERE a.IDSTUDENT != b.IDSTUDENT)
ORDER BY BDAY;