USE UNIVER;

SELECT FACULTY.FACULTY Факультет, GROUPS.PROFESSION Специальность, PROGRESS.SUBJECT Дисциплина, PROGRESS.NOTE
FROM FACULTY INNER JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT

SELECT FACULTY.FACULTY Факультет, GROUPS.PROFESSION Специальность, PROGRESS.SUBJECT Дисциплина, sum(PROGRESS.NOTE) [Средняя оценка]
FROM FACULTY INNER JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
WHERE FACULTY.FACULTY = 'ИТ'
GROUP BY ROLLUP(FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT);

SELECT FACULTY.FACULTY Факультет, GROUPS.PROFESSION Специальность, PROGRESS.SUBJECT Дисциплина, AVG(PROGRESS.NOTE) [Средняя оценка]
FROM FACULTY INNER JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
WHERE FACULTY.FACULTY = 'ИТ'
GROUP BY CUBE(FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT);

SELECT GROUPS.PROFESSION Специальность, PROGRESS.SUBJECT Дисциплина, AVG(PROGRESS.NOTE) [Средняя оценка]
FROM GROUPS INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT
HAVING GROUPS.PROFESSION = '1-47 01 01' Or GROUPS.PROFESSION = '1-40 01 02'
	UNION all
SELECT GROUPS.PROFESSION Специальность, PROGRESS.SUBJECT Дисциплина, AVG(PROGRESS.NOTE) [Средняя оценка]
FROM GROUPS INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT
HAVING GROUPS.PROFESSION = '1-40 01 02';

SELECT GROUPS.PROFESSION Специальность, PROGRESS.SUBJECT Дисциплина, AVG(PROGRESS.NOTE) [Средняя оценка]
FROM GROUPS INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT
HAVING GROUPS.PROFESSION = '1-47 01 01'
	INTERSECT
SELECT GROUPS.PROFESSION Специальность, PROGRESS.SUBJECT Дисциплина, AVG(PROGRESS.NOTE) [Средняя оценка]
FROM GROUPS INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT;

SELECT GROUPS.PROFESSION Специальность, PROGRESS.SUBJECT Дисциплина, AVG(PROGRESS.NOTE) [Средняя оценка]
FROM GROUPS INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT
	EXCEPT
SELECT GROUPS.PROFESSION Специальность, PROGRESS.SUBJECT Дисциплина, AVG(PROGRESS.NOTE) [Средняя оценка]
FROM GROUPS INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT
HAVING GROUPS.PROFESSION = '1-47 01 01'